const DEFAULT_CONDITIONS = [
    { name: 'Blinded', kind: 'debuff', description: 'Cannot see. Automatically fails sight-based checks. Attacks against it have advantage; its attacks have disadvantage.', source: '5e' },
    { name: 'Charmed', kind: 'debuff', description: 'Cannot attack the charmer. The charmer has advantage on social checks against it.', source: '5e' },
    { name: 'Deafened', kind: 'debuff', description: 'Cannot hear. Automatically fails hearing-based checks.', source: '5e' },
    { name: 'Exhaustion', kind: 'debuff', description: 'Level-based exhaustion. Track the level on the effect.', hasLevels: true, maxLevel: 6, source: '5e' },
    { name: 'Frightened', kind: 'debuff', description: 'Disadvantage on ability checks and attacks while source is in sight. Cannot willingly move closer to source.', source: '5e' },
    { name: 'Grappled', kind: 'debuff', description: 'Speed becomes 0. Ends if grappler is incapacitated or target escapes.', source: '5e' },
    { name: 'Incapacitated', kind: 'debuff', description: 'Cannot take actions or reactions.', source: '5e' },
    { name: 'Invisible', kind: 'buff', description: 'Cannot be seen without special senses. Attacks against it have disadvantage; its attacks have advantage.', source: '5e' },
    { name: 'Paralyzed', kind: 'debuff', description: 'Incapacitated, cannot move or speak, fails Strength and Dexterity saves. Attacks have advantage; close hits are critical.', source: '5e' },
    { name: 'Petrified', kind: 'debuff', description: 'Transformed into stone, incapacitated, unaware, resistant to all damage.', source: '5e' },
    { name: 'Poisoned', kind: 'debuff', description: 'Disadvantage on attack rolls and ability checks.', source: '5e' },
    { name: 'Prone', kind: 'debuff', description: 'Only crawling movement. Disadvantage on attacks. Melee attacks against it have advantage; ranged attacks have disadvantage.', source: '5e' },
    { name: 'Restrained', kind: 'debuff', description: 'Speed 0. Disadvantage on attacks and Dexterity saves. Attacks against it have advantage.', source: '5e' },
    { name: 'Stunned', kind: 'debuff', description: 'Incapacitated, cannot move, speaks falteringly, fails Strength and Dexterity saves. Attacks have advantage.', source: '5e' },
    { name: 'Unconscious', kind: 'debuff', description: 'Incapacitated, cannot move or speak, unaware, drops held items, falls prone, fails Strength and Dexterity saves.', source: '5e' },
    { name: 'Sickened', kind: 'debuff', description: 'Disadvantage on Constitution saves. Removed by the same effects as poison.', source: 'homebrew' },
    { name: 'Defenseless', kind: 'debuff', description: 'Attack rolls against this creature have advantage.', source: 'homebrew' },
    { name: 'Impaired', kind: 'debuff', description: 'Speed is halved.', source: 'homebrew' },
    { name: 'Distracted', kind: 'debuff', description: 'Cannot take reactions.', source: 'homebrew' },
    { name: 'Hexblade_Curse', kind: 'debuff', description: 'Nif deals extra necrotic damage, crits easier, and heals if the target dies.', source: 'homebrew' },
    { name: 'Moonlit', kind: 'debuff', description: 'Produces moonlight in a 20 ft radius and cannot be invisible.', source: 'homebrew' },
    { name: 'Confused', kind: 'debuff', description: 'Cannot take bonus actions or reactions and rolls behavior at the start of turn.', source: 'homebrew' },
    { name: 'Insanity', kind: 'debuff', description: 'Level-based divine or psychic madness. Track the level on the effect.', hasLevels: true, maxLevel: 6, source: 'homebrew' },
    { name: 'Divine_Ire', kind: 'debuff', description: 'Level-based divine punishment. Track the level on the effect.', hasLevels: true, maxLevel: 6, source: 'homebrew' },
    { name: 'Divine_Ire_Cyric', kind: 'debuff', description: 'Level-based divine punishment from Cyric. Track the level on the effect.', hasLevels: true, maxLevel: 6, source: 'homebrew' },
    { name: 'Penance', kind: 'debuff', description: 'Judgement by angels. Can be reduced to add righteous damage.', hasLevels: true, maxLevel: 20, source: 'homebrew' },
    { name: 'Hasted', kind: 'buff', description: 'Double speed, +2 AC, advantage on Dexterity saves, and a limited extra action.', source: 'homebrew' },
    { name: 'Inspired', kind: 'buff', description: 'Bardic Inspiration or similar bonus die.', source: 'homebrew' },
    { name: 'Heroic_Inspiration', kind: 'buff', description: 'A d20 reroll.', source: 'homebrew' },
    { name: 'Spirit_Shroud', kind: 'buff', description: 'Extra damage and enemy movement reduction.', source: 'homebrew' },
    { name: 'Tensor_Transformation', kind: 'buff', description: 'Super-powered wizard transformation.', source: 'homebrew' },
    { name: 'Retaliation_Aura', kind: 'buff', description: 'Punch back.', source: 'homebrew' },
    { name: 'Foresight', kind: 'buff', description: 'Broad advantage from foresight magic.', source: 'homebrew' },
    { name: 'Elder_Champion', kind: 'buff', description: 'Spells as bonus actions, recurring healing, and stronger saves against spells.', source: 'homebrew' },
    { name: 'Celestial_Revelation', kind: 'buff', description: 'Flight, damage aura, or fear aura.', source: 'homebrew' },
    { name: 'Power_of_Mercy', kind: 'buff', description: 'Resistance to everything and radiant retaliation.', source: 'homebrew' },
    { name: 'Sacred_Divine_Sense', kind: 'buff', description: 'Epic advantage against fiends, undead, celestials and daemons.', source: 'homebrew' },
    { name: 'Protective_Spirit', kind: 'buff', description: 'Heals if bloodied at end of round.', source: 'homebrew' },
    { name: 'Emissary_of_Redemtion', kind: 'buff', description: 'Half damage from creatures not yet attacked and radiant retaliation.', source: 'homebrew' },
    { name: 'Raging', kind: 'buff', description: 'Barbarian rage or similar resistance/damage mode.', source: 'homebrew' },
    { name: 'Dodging', kind: 'buff', description: 'Taking the Dodge action.', source: 'homebrew' },
    { name: 'Concentrating', kind: 'neutral', description: 'Maintaining concentration on a spell or feature.', source: 'homebrew' },
    { name: 'Marked', kind: 'neutral', description: 'Marked for tracking or a special effect.', source: 'homebrew' }
];

module.exports = {
    DEFAULT_CONDITIONS
};
